// port-lint: source landlock/src/uapi/landlock_all.rs
package io.github.kotlinmania.landlock.uapi

// Automatically generated by rust-bindgen 0.72.0.

const val LANDLOCK_CREATE_RULESET_VERSION: UInt = 1u
const val LANDLOCK_ACCESS_FS_EXECUTE: UInt = 1u
const val LANDLOCK_ACCESS_FS_WRITE_FILE: UInt = 2u
const val LANDLOCK_ACCESS_FS_READ_FILE: UInt = 4u
const val LANDLOCK_ACCESS_FS_READ_DIR: UInt = 8u
const val LANDLOCK_ACCESS_FS_REMOVE_DIR: UInt = 16u
const val LANDLOCK_ACCESS_FS_REMOVE_FILE: UInt = 32u
const val LANDLOCK_ACCESS_FS_MAKE_CHAR: UInt = 64u
const val LANDLOCK_ACCESS_FS_MAKE_DIR: UInt = 128u
const val LANDLOCK_ACCESS_FS_MAKE_REG: UInt = 256u
const val LANDLOCK_ACCESS_FS_MAKE_SOCK: UInt = 512u
const val LANDLOCK_ACCESS_FS_MAKE_FIFO: UInt = 1024u
const val LANDLOCK_ACCESS_FS_MAKE_BLOCK: UInt = 2048u
const val LANDLOCK_ACCESS_FS_MAKE_SYM: UInt = 4096u
const val LANDLOCK_ACCESS_FS_REFER: UInt = 8192u
const val LANDLOCK_ACCESS_FS_TRUNCATE: UInt = 16384u
const val LANDLOCK_ACCESS_FS_IOCTL_DEV: UInt = 32768u
const val LANDLOCK_ACCESS_NET_BIND_TCP: UInt = 1u
const val LANDLOCK_ACCESS_NET_CONNECT_TCP: UInt = 2u
const val LANDLOCK_SCOPE_ABSTRACT_UNIX_SOCKET: UInt = 1u
const val LANDLOCK_SCOPE_SIGNAL: UInt = 2u

typealias S32 = Int
typealias U64 = ULong

/**
 * Mirrors the Landlock ruleset attributes accepted by the create-ruleset system call.
 *
 * Kotlin does not control struct layout, so the fields here are a value carrier only; the native
 * layout is the responsibility of the platform-specific system-call wrapper.
 */
data class LandlockRulesetAttr(
    var handledAccessFs: U64,
    var handledAccessNet: U64,
    var scoped: U64,
)

typealias LandlockRuleType = UInt

const val LANDLOCK_RULE_TYPE_LANDLOCK_RULE_PATH_BENEATH: LandlockRuleType = 1u
const val LANDLOCK_RULE_TYPE_LANDLOCK_RULE_NET_PORT: LandlockRuleType = 2u

/**
 * Mirrors the Landlock path-beneath attributes accepted by the add-rule system call with a
 * path-beneath rule type.
 *
 * Kotlin does not control struct layout; the packed native representation must be reproduced
 * inside the system-call wrapper.
 */
data class LandlockPathBeneathAttr(
    var allowedAccess: U64,
    var parentFd: S32,
)

/**
 * Mirrors the Landlock network-port attributes accepted by the add-rule system call with a
 * network-port rule type.
 */
data class LandlockNetPortAttr(
    var allowedAccess: U64,
    var port: U64,
)
